# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField()),
                ('file', models.CharField(max_length=400)),
                ('source', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('trackNumber', models.IntegerField(default=0)),
                ('totalTrackCount', models.IntegerField(default=0)),
                ('now', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('skip', models.IntegerField(default=0)),
                ('repeat', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
